### ISSUE TITLE
crashing for me

### ISSUE THREAD

**Issue by PeterPePem** [PlutoSolutions/Boze#7]
crashs when i open clickgui

**Comment by mr-nv** [comment]
whats the crash log

**Comment by mr-nv** [comment]
check the font at .minecraft/boze/fonts/lexend.ttf, check if it exists and its not 0 bytes
my friend crashed because for some reason his font was 0 bytes

**Comment by PeterPePem** [comment]
thxx, it wass 0 bytes lol
